# Use the official Node.js image as the base image
FROM node:17

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 to allow outside access
EXPOSE 3005

# Start the frontend application using npm start
CMD ["npm", "start"]